configs:
  - stockexchange: "SZ"
    stockexchangecode: 100
    companyinfourl: "http://www.szse.cn/api/report/ShowReport/data?SHOWTYPE=JSON&CATALOGID=1110x"
    stockinfourl: "http://www.szse.cn/api/market/ssjjhq/getTimeData?random=0.20171192356322387&marketId=1&code=000001"
    realtimeinfourl: ""
  - stockexchange: "SH"
    stockexchangecode: 130
    companyinfourl: ""
    stockinfourl: ""
    realtimeinfourl: ""
  - stockexchange: "HK"
    stockexchangecode: 160
    companyinfourl: ""
    stockinfourl: ""
    realtimeinfourl: ""
